// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Contributor is the predicate function for contributor builders.
type Contributor func(*sql.Selector)
