// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/internal/server/ent/contributor"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContributorCreate is the builder for creating a Contributor entity.
type ContributorCreate struct {
	config
	mutation *ContributorMutation
	hooks    []Hook
}

// SetFirstName sets the "first_name" field.
func (cc *ContributorCreate) SetFirstName(s string) *ContributorCreate {
	cc.mutation.SetFirstName(s)
	return cc
}

// SetLastName sets the "last_name" field.
func (cc *ContributorCreate) SetLastName(s string) *ContributorCreate {
	cc.mutation.SetLastName(s)
	return cc
}

// SetEmail sets the "email" field.
func (cc *ContributorCreate) SetEmail(s string) *ContributorCreate {
	cc.mutation.SetEmail(s)
	return cc
}

// Mutation returns the ContributorMutation object of the builder.
func (cc *ContributorCreate) Mutation() *ContributorMutation {
	return cc.mutation
}

// Save creates the Contributor in the database.
func (cc *ContributorCreate) Save(ctx context.Context) (*Contributor, error) {
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ContributorCreate) SaveX(ctx context.Context) *Contributor {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ContributorCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ContributorCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ContributorCreate) check() error {
	if _, ok := cc.mutation.FirstName(); !ok {
		return &ValidationError{Name: "first_name", err: errors.New(`ent: missing required field "Contributor.first_name"`)}
	}
	if _, ok := cc.mutation.LastName(); !ok {
		return &ValidationError{Name: "last_name", err: errors.New(`ent: missing required field "Contributor.last_name"`)}
	}
	if _, ok := cc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Contributor.email"`)}
	}
	return nil
}

func (cc *ContributorCreate) sqlSave(ctx context.Context) (*Contributor, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ContributorCreate) createSpec() (*Contributor, *sqlgraph.CreateSpec) {
	var (
		_node = &Contributor{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(contributor.Table, sqlgraph.NewFieldSpec(contributor.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.FirstName(); ok {
		_spec.SetField(contributor.FieldFirstName, field.TypeString, value)
		_node.FirstName = value
	}
	if value, ok := cc.mutation.LastName(); ok {
		_spec.SetField(contributor.FieldLastName, field.TypeString, value)
		_node.LastName = value
	}
	if value, ok := cc.mutation.Email(); ok {
		_spec.SetField(contributor.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	return _node, _spec
}

// ContributorCreateBulk is the builder for creating many Contributor entities in bulk.
type ContributorCreateBulk struct {
	config
	err      error
	builders []*ContributorCreate
}

// Save creates the Contributor entities in the database.
func (ccb *ContributorCreateBulk) Save(ctx context.Context) ([]*Contributor, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Contributor, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContributorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ContributorCreateBulk) SaveX(ctx context.Context) []*Contributor {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ContributorCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ContributorCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
